In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        50 non-null     int64 
 1   gender     50 non-null     object
 2   review     50 non-null     object
 3   education  50 non-null     object
 4   purchased  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB


In [4]:
df.sample(5)

age  gender review education purchased
49   25  Female   Good        UG        No
7    60  Female   Poor    School       Yes
14   15    Male   Poor        PG       Yes
15   75    Male   Poor        UG        No
43   27    Male   Poor        PG        No

* Education : Ordinal categorical we apply Ordinal encoder
* review : Oridinal categorical we apply Ordinal encoder
* Age : Numeric variable
* gender : Nominal categorical  we apply One hot encoder
* purchased : Nominal categorical we apply One Label encoder

In [5]:
# we just using review,education,purchased removing 'age' column its an 'integer' data set
df = df.iloc[:,2:]

In [6]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [8]:
X_train.head()

review education
15     Poor        UG
37  Average        PG
5   Average    School
1      Poor        UG
14     Poor        PG

In [9]:
#Its a purchased column
y_train.head()

15     No
37    Yes
5     Yes
1      No
14    Yes
Name: purchased, dtype: object

In [10]:
from sklearn.preprocessing import OrdinalEncoder

##### If we want to convert the data we need to create how many Categories data set in our account  with in a Proper Categories

In [11]:
# For a 'review' and 'education' columns we were converting data in a proper way
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [12]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [13]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [14]:
X_train

array([[0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 1.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [2., 1.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [2., 2.],
       [0., 0.],
       [1., 2.],
       [0., 1.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 0.]])

In [15]:
# For checking Categories
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# Purchased column
* It is not used for the "Input values" and used for encoding target valus

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le = LabelEncoder()

In [18]:
le.fit(y_train)

LabelEncoder()

In [19]:
# For checking Categories in the data set
le.classes_

array(['No', 'Yes'], dtype=object)

In [20]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [21]:
y_train

array([0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0])

In [22]:
y_test

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0])